// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

#include <string>

char findTheDifference(std::string s, std::string t) {
    int sSum = 0;
    int tSum = 0;
    for (int i = 0; i < size(s); i++) {
        sSum += s[i];
    }
    for (int j = 0; j < size(t); j++) {
        tSum += t[j];
    }
    return (char) (tSum-sSum);
}
